name: mapstyler_workspace
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

workspace:
  - mapstyler_style
  - mapbox4dart
  - mapstyler_mapbox_adapter
  - mapstyler_sld_adapter
  - qml4dart
  - mapstyler_qml_adapter
  - flutter_mapstyler
